# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [29]:
import numpy as np
x=np.ones((5,5), dtype=int) * 6
print('Expected OutputOriginal array \n', x)

for i in range(5):
    for j in range(5):
        if (i > 0 and i <4) and (j > 0 and j <4):
            x[j,i]=0
print('6 on the border and 0 inside in the array \n ', x)

Expected OutputOriginal array 
 [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array 
  [[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [30]:
x= np.ones((8,8),dtype=int)*3
x[1::2,::2]=9
x[::2, 1::2]=9
x

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [31]:
x = np.empty((3,4))
print(x)
y=np.full((3,3),6)
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [32]:
x=np.array([-17.77777778,-11.11111111,7.33888889,1.11111111,37.72777778])
y= (9*x+ (32 * 5))/5
np.set_printoptions(suppress=True)
print("Expected OutputValues in Fahrenheit degrees-  \n ",  y)
print("Values in Centigrade degrees- \n " ,x)

Expected OutputValues in Fahrenheit degrees-  
  [-0.   12.   45.21 34.   99.91]
Values in Centigrade degrees- 
  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [33]:
x=np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print("Real Part of the array- \n", x.real)
print("Imaginary Part of the array- \n", x.imag)

Real Part of the array- 
 [1.         0.70710678]
Imaginary Part of the array- 
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [34]:
Array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",Array1)
Array2 = [0, 40]
print("Array2: ",Array2)
print("Compare each element of array1 and array2")
print(np.in1d(Array1, Array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [35]:
Array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",Array1)
Array2 = [10, 30, 40]
print("Array2: ",Array2)
print("Common values between two arrays-")
print(np.intersect1d(Array1, Array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays-
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [36]:
x=np.array([10, 10, 20, 20, 30, 30])
print("Expected OutputOriginal array- \n",x)
print("Unique elements of the above array- \n", np.unique(x))
y=np.array([[1, 1],[2, 3]])
print("Original array- \n",y)
print("Unique elements of the above array- \n", np.unique(y))

Expected OutputOriginal array- 
 [10 10 20 20 30 30]
Unique elements of the above array- 
 [10 20 30]
Original array- 
 [[1 1]
 [2 3]]
Unique elements of the above array- 
 [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [37]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = np.array([10, 30, 40, 50, 70])
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays- \n" , np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays- 
 [ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [38]:
print(np.all([[True,False],[True,True]]))
print(np.all([[1,2],[3,4]]))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [39]:
print(np.any([[False,True],[False,False]],axis=0))
print(np.any([1, 2, -3]))
print(np.any([[False,True],[False,False]],axis=1))

[False  True]
True
[ True False]


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [40]:
x = np.array([1, 2, 3, 4])
print("Original array \n", x)
print("Repeating 2 times \n", np.tile(x, 2))
print("Repeating 3 times \n", np.tile(x, 3))

Original array 
 [1 2 3 4]
Repeating 2 times 
 [1 2 3 4 1 2 3 4]
Repeating 3 times 
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [41]:
x=np.array([1,2,3,4,5,6])
print ("Original array-  ", x)
print("maximum values- ", np.argmax(x))
print("maximum values- ", np.argmin(x))

Original array-   [1 2 3 4 5 6]
maximum values-  5
maximum values-  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [42]:
a=np.array([1,2])
b=np.array([4,5])
print("Array a- ", a)
print("Array b- ",b)
print("a >b \n",(a>b))
print("a >= b \n",(a>=b))
print("a < b \n",(a<b))
print("a <= b \n",(a<=b))

Array a-  [1 2]
Array b-  [4 5]
a >b 
 [False False]
a >= b 
 [False False]
a < b 
 [ True  True]
a <= b 
 [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [43]:
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort a along the first axis- ")
x = np.sort(a, axis=0)
print(x)
print("Sort x along the last axis- ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort a along the first axis- 
[[2 1]
 [4 6]]
Sort x along the last axis- 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [44]:
first_names =  ( 'Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery' )
last_names = ( 'Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum' )
x = np.lexsort((first_names, last_names))
print(x)

[0 1 2 3 4]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [45]:
x=np.array([[0,10,20],[20,30,40]])
print("Original array- \n",x)
print("Values bigger than 10 =", x[x>10])
print('Their indices are ', np.nonzero(x>10))

Original array- 
 [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [46]:
x=np.ones((4,4))
print ( "%d bytes" % (x.size * x.itemsize))

128 bytes


## Great Job!